#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


poetry run python /app/manage.py collectstatic --noinput
poetry run python manage.py migrate
poetry run python manage.py loaddata master_fixture.json

exec poetry run uvicorn config.asgi:application \
                --host 0.0.0.0 \
                --port 8000 \
                --app-dir /app
