#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


poetry run python /app/manage.py collectstatic --noinput
poetry run python manage.py migrate
poetry run python manage.py loaddata master_fixture.json

exec poetry run /usr/local/bin/gunicorn config.asgi \
    --bind 0.0.0.0:5000 \
    --chdir=/app -k uvicorn.workers.UvicornWorker
