#!/bin/bash

set -o errexit
set -o nounset

./wait-for-it.sh -t 120 django:8000 -- echo "Website is ready, spooling celery flower"

exec poetry run celery \
    -A config.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
