# Generated by Django 5.0.6 on 2024-05-23 00:28

import address.models
import django.db.models.deletion
import modelcluster.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('volunteer_registration_open', models.DateField(verbose_name='Volunteer Registration Open')),
                ('volunteer_registration_close', models.DateField(verbose_name='Volunteer Registration Close')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='volunteering.event')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('is_quarantined', models.BooleanField(default=False, verbose_name='Is Quarantined')),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Deletion Date')),
                ('primary_contact_name', models.CharField(max_length=128, verbose_name='Primary Contact Name')),
                ('primary_contact_email', models.EmailField(max_length=254, verbose_name='Primary Contact Email')),
                ('primary_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Primary Contact Phone Number')),
                ('secondary_contact_name', models.CharField(blank=True, max_length=128, verbose_name='Secondary Contact Name')),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Secondary Contact Email')),
                ('secondary_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Secondary Contact Phone Number')),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Mailing Address')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('activity', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteering.activity')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Primary Phone Number')),
                ('secondary_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Secondary Phone Number')),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Mailing Address')),
                ('organization', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='volunteering.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('volunteer_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='volunteering.volunteer')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationShiftRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteering.organization')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='volunteering.shift')),
            ],
            options={
                'abstract': False,
                'unique_together': {('organization', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationOwnersRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='volunteering.organization')),
                ('owner', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to='volunteering.volunteer')),
            ],
            options={
                'abstract': False,
                'unique_together': {('organization', 'owner')},
            },
        ),
    ]
