# Generated by Django 5.0.6 on 2024-05-09 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOrganization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Volunteer Organization',
                'verbose_name_plural': 'Volunteer Organizations',
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='VolunteerOrganizationOwner',
            fields=[
                ('organizationowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organizationowner')),
            ],
            options={
                'verbose_name': 'Volunteer Organization Owner',
                'verbose_name_plural': 'Volunteer Organization Owners',
            },
            bases=('organizations.organizationowner',),
        ),
        migrations.CreateModel(
            name='VolunteerOrganizationUser',
            fields=[
                ('organizationuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.organizationuser')),
            ],
            options={
                'verbose_name': 'Volunteer Organization User',
                'verbose_name_plural': 'Volunteer Organization Users',
            },
            bases=('organizations.organizationuser',),
        ),
    ]
