# Generated by Django 5.0.6 on 2024-05-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_time', models.DateTimeField(verbose_name='End Date & Time')),
                ('name', models.CharField(verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organizations', models.ManyToManyField(blank=True, related_name='shifts', to='volunteering.volunteerorganization')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time', 'end_time', 'name'],
            },
        ),
    ]
