# Generated by Django 5.0.7 on 2024-07-14 01:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Primary Contact Cell Number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='secondary_contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Secondary Contact Cell Number'),
        ),
    ]
