# Generated by Django 5.0.6 on 2024-05-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0002_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('shifts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteering.shift')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
