# Generated by Django 5.0.7 on 2024-07-22 00:41

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0008_translation_support'),
        ('volunteering', '0002_alter_organization_primary_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteeringCampaign',
            fields=[
                ('campaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='birdsong.campaign')),
                ('body', wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'document-link'], template='birdsong/mail/blocks/richtext.html'))])),
            ],
            bases=('birdsong.campaign',),
        ),
    ]
