# Generated by Django 5.0.6 on 2024-05-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0003_alter_shift_name_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='shifts',
        ),
        migrations.AddField(
            model_name='shift',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='volunteering.activity'),
        ),
    ]
