# Generated by Django 5.0.7 on 2024-08-01 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0004_alter_volunteer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='first_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='volunteering.shift', verbose_name='First Activity'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notable_skills',
            field=models.TextField(blank=True, verbose_name='Notable Skills'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='volunteering.shift', verbose_name='Second Activity'),
        ),
        migrations.AddField(
            model_name='organization',
            name='third_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='volunteering.shift', verbose_name='Third Activity'),
        ),
    ]
