# Generated by Django 5.0.7 on 2024-08-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0005_organization_first_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='secondary_activity',
            new_name='second_activity',
        ),
    ]
