# Generated by Django 5.0.7 on 2024-08-01 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0007_shift_name_alter_shift_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='first_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='volunteering.activity', verbose_name='First Activity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='second_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='volunteering.activity', verbose_name='Second Activity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='third_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='volunteering.activity', verbose_name='Third Activity'),
        ),
    ]
