# Generated by Django 5.0.7 on 2024-09-01 17:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0008_alter_organization_first_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='primary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Cell Phone Number'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Organization/Home Phone Number'),
        ),
    ]
